<?php

/**
 * @file
 * Implementation of CBU library scholar customizations.
 */



/**
 * Implements hook_islandora_ingest_steps_alter().
 */
function cbu_scholar_customizations_ir_citationCModel_islandora_ingest_steps_alter(array &$steps, array &$form_state) {
  $steps['islandora_scholar_file_upload'] = array(
    'weight' => 10,
    'type' => 'form',
    'form_id' => 'cbu_scholar_customizations_pdf_upload_form',
    'module' => 'cbu_scholar_customizations',
    'file' => 'includes/pdf_upload.form.inc',
  );
}

/**
 * Implements hook_islandora_ingest_steps_alter().
 */
function cbu_scholar_customizations_ir_thesisCModel_islandora_ingest_steps_alter(array &$steps, array &$form_state) {
  $steps['islandora_scholar_file_upload'] = array(
    'weight' => 10,
    'type' => 'form',
    'form_id' => 'cbu_scholar_customizations_pdf_upload_form',
    'module' => 'cbu_scholar_customizations',
    'file' => 'includes/pdf_upload.form.inc',
  );
}


function cbu_scholar_customizations_form_islandora_scholar_upload_form_alter(&$form, $form_state, $form_id) {
  module_load_include('inc', 'cbu_scholar_customizations', 'includes/pdf_upload.form');
  $usage = cbu_scholar_customizations_get_use_permissions();
  $form['upload_document']['usage']['#options'] = $usage;
  $versions = cbu_scholar_customizations_get_document_versions();
  $form['upload_document']['version']['#options'] = $versions;
  // Call our submit handler not scholars We are using different attributes for usage etc.
  $form['#submit'] = array('cbu_scholar_customizations_scholar_upload_form_submit');

  return $form;
}

/**
 * Upload form Submit handler, adds PDF datastream.
 *
 * Also updates the MODS usage and version for the PDF datastream.
 *
 * We override the scholars version of this function so we can use our own usage and version attributes.
 *
 * @param array $form
 *   The Drupal form definition.
 * @param array $form_state
 *   The Drupal form state.
 */
function cbu_scholar_customizations_scholar_upload_form_submit(array $form, array &$form_state) {
  extract($form_state['values']);
  $object = islandora_object_load($pid);

  try {
    $datastream = $object->constructDatastream($dsid, 'M');
    $datastream->label = 'PDF Datastream';
    $datastream->mimetype = 'application/pdf';
    $file = file_load($file);
    $path = drupal_realpath($file->uri);
    $datastream->setContentFromFile($path);

    $object->ingestDatastream($datastream);
    module_load_include('inc', 'cbu_scholar_customizations', 'includes/upload.tab');
    cbu_scholar_customizations_add_usage_and_version_elements_to_mods($object, $usage, $version);
  }
  catch (Exception $e) {
    drupal_set_message(t('@message', array('@message' => check_plain($e->getMessage()))), 'error');
  }
}


